Harmful Plant Page
codersforcauses/bfa-rescue pull request #23
Opened 2020-12-20 04:20 UTC by Hanchooi

Need to direct ".../common-garden-plants-harmful-to-dogs/" to this page.

2020-12-21 06:31 UTC, Drewbi requested changes
Looks good style wise, just has some issues to resolve

2020-12-21 06:31 UTC, Drewbi commented on client/components/poison/PoisonCard.vue
> +    <v-card-text align="center" v-html="carddescription">
Do we actually need to use v-html? It doesn't look like we have any rendered content besides text.

2020-12-21 06:31 UTC, Drewbi commented on client/components/poison/PoisonTop.vue
> +<template>
I think it's highly unlikely for us to ever need more than one Header so i would recommend transferring this content to the main poison page file and using static text instead of keeping it in data.

2020-12-21 06:31 UTC, Drewbi commented on client/pages/poisonous plant.vue
> +<template>
using spaces in file names is pretty unconventional and we need this page to somewhat match the routing they have on the other website so i would recommend renaming to `harmful_plants.vue`

2020-12-21 06:31 UTC, Drewbi commented on client/pages/poisonous plant.vue
> +            'https://secureservercdn.net/160.153.138.177/wzj.f59.myftpupload.com/wp-content/uploads/2015/08/puppy-in-garden.jpg',
We shouldn't rely on their cdn for these images. It would be best to download them to the assets folder until we upload them to our own image cdn. Also the images aren't coming through on the preview deployment and running the project locally has issues with server/client html mismatch. I would guess it could be to do with using v-html attributes.

2020-12-29 10:48 UTC, Hanchooi commented
Hi, Drubi. So sorry for the delay, has been holidaying past few days. Will look into this and get them fix this week. Thank you so much for the review.

2021-01-03 09:48 UTC, Hanchooi commented on client/pages/poisonous plant.vue
> +<template>
Done. Renamed

2021-01-03 09:49 UTC, Hanchooi commented on client/components/poison/PoisonTop.vue
> +<template>
Done.

2021-01-03 09:49 UTC, Hanchooi commented on client/components/poison/PoisonCard.vue
> +    <v-card-text align="center" v-html="carddescription">
Done.

2021-01-03 09:50 UTC, Hanchooi commented on client/pages/poisonous plant.vue
> +            'https://secureservercdn.net/160.153.138.177/wzj.f59.myftpupload.com/wp-content/uploads/2015/08/puppy-in-garden.jpg',
I have removed v-html attributes. Shall we temporarily use their cdn until we upload images to our own image cdn ?

2021-01-03 12:24 UTC, Drewbi commented
Looking good, just a stylistic recommendation, currently the title of the plant and the "symptoms" are on the same level in terms of text size. Adding a class of `text-body-1` would allow for more clarity:
<img width="672" alt="Screen Shot 2021-01-03 at 8 21 38 pm" src="https://user-images.githubusercontent.com/38243574/103478428-93690800-4e01-11eb-917a-2286c4f116f8.png">

2021-01-03 12:25 UTC, Drewbi commented on client/pages/poisonous plant.vue
> +            'https://secureservercdn.net/160.153.138.177/wzj.f59.myftpupload.com/wp-content/uploads/2015/08/puppy-in-garden.jpg',
Yeah thats alright, Could you create a github issue for the re-uploading task?

2021-01-03 12:26 UTC, Drewbi requested changes

2021-01-03 12:26 UTC, Drewbi commented on client/components/poison/PoisonCard.vue
> +    <v-card-title class="justify-center"> Symptoms if ingested: </v-card-title>
Add `text-body-1` to the classes

2021-01-09 05:12 UTC, Hanchooi commented on client/pages/poisonous plant.vue
> +            'https://secureservercdn.net/160.153.138.177/wzj.f59.myftpupload.com/wp-content/uploads/2015/08/puppy-in-garden.jpg',
Done. I hope I did this correctly ? XD

2021-01-09 05:13 UTC, Hanchooi commented on client/components/poison/PoisonCard.vue
> +    <v-card-title class="justify-center"> Symptoms if ingested: </v-card-title>
tried "text-body-1", added "font-weight-medium" instead. Seems better.

2021-01-18 06:56 UTC, Drewbi commented on client/components/poison/PoisonCard.vue
> +    <v-card-title class="justify-center"> Symptoms if ingested: </v-card-title>
Not seeing any changes here, did you push your code?

2021-01-21 03:18 UTC, Hanchooi commented on client/components/poison/PoisonCard.vue
> +    <v-card-title class="justify-center"> Symptoms if ingested: </v-card-title>
ah, oops. Just pushed. ><

2021-01-26 18:20 UTC, Drewbi approved these changes

2021-01-26 18:21 UTC, merged

2021-01-26 18:21 UTC, Drewbi commented
Made a few minor changes and merged this. Well done :)