Finished supporters page
codersforcauses/bfa-rescue pull request #26
Opened 2021-01-06 16:35 UTC by bpgoodwin

**Created the supporters page following the old site.** 

- Added buttons linking to respective businesses.
- Updated some of the older / low quality images.
- Separated the hero graphic into a vue component for other pages if wanted.

2021-01-11 15:46 UTC, noobling approved these changes

2021-01-11 15:46 UTC, noobling commented on client/components/Hero.vue
> +@media only screen and (max-width: 768px) {
You can use media queries but you might find it easier with vuetify's breakpoint service object https://vuetifyjs.com/en/features/breakpoints/#breakpoint-service

2021-01-11 15:46 UTC, noobling commented on client/pages/supporters.vue
> +<style lang="scss">
Please use `scoped` to not impact other components

2021-01-11 15:46 UTC, noobling commented on client/pages/supporters.vue
> +            <v-card class="smallcard">
Theres a lot of repeated code here. I would recommend you use a `v-for` here is an example of this pattern https://github.com/codersforcauses/bfa-rescue/blob/f31603ef8c3be5940d8a0cabecf55f25acc9c81d/client/pages/health.vue

2021-01-14 03:23 UTC, bpgoodwin commented on client/pages/supporters.vue
> +<style lang="scss">
Added

2021-01-14 03:26 UTC, bpgoodwin commented on client/pages/supporters.vue
> +            <v-card class="smallcard">
Thanks for the feedback, still learning getting used to the Vue way of doing things. Changed the page to reflect your suggestions & added the a card component.

2021-01-14 03:33 UTC, bpgoodwin commented on client/components/Hero.vue
> +@media only screen and (max-width: 768px) {
Is this ok to leave in? Tried using the Vue feature you outlined but the way I implemented it wasn't as succinct as is currently.

2021-01-14 15:51 UTC, noobling commented on client/components/Hero.vue
> +@media only screen and (max-width: 768px) {
Yeah its fine just mentioned it incase you weren't aware

2021-01-14 15:52 UTC, noobling commented on client/pages/supporters.vue
> +            <v-card class="smallcard">
Thanks hopefully that makes sense why we would want to do that

2021-01-15 06:21 UTC, Drewbi requested changes

2021-01-15 06:21 UTC, Drewbi commented on client/components/Supporters/Card.vue
> +  <v-card class="mx-auto flex flex-column">
Because vcard is adding it's own layout, using mx-auto and flex-column is unneeded.

2021-01-15 06:21 UTC, Drewbi commented on client/components/Supporters/Card.vue
> +      :src="require('@/assets/' + imagelink + '')"
```suggestion
      :src="require('@/assets/' + imagelink)"
```

2021-01-15 06:21 UTC, Drewbi commented on client/pages/supporters.vue
> +<style scoped lang="scss">
```suggestion
<style scoped>
```

2021-01-15 06:21 UTC, Drewbi commented on client/pages/supporters.vue
> +          imagelink: 'sponsors/nola-criddle-foundation.jpg',
Thanks for making custom sponsor cards, they work as a placeholder but we should change them for something lighter in a sans serif font at some point

2021-01-19 04:07 UTC, Drewbi requested changes
Getting there :)

2021-01-19 04:07 UTC, Drewbi commented on client/pages/supporters.vue
> +.full-width {
If you pull from master it should be much easier to make the heading full width, take a look at the health nav page code for an example

2021-01-19 04:07 UTC, Drewbi commented on client/components/Supporters/Hero.vue
> +    text: { type: String, default: '' },
Keep a consistent new line practice for extra clean code:

```
title: {
    type: String,
    default: '',
}
```

2021-01-19 04:07 UTC, Drewbi commented on client/components/Supporters/Hero.vue
> +<style scoped lang="scss">
```suggestion
<style scoped>
```

2021-01-19 04:07 UTC, Drewbi commented on client/components/Supporters/Hero.vue
> +        <div class="hero-btn mt-5">
`hero-btn` is not defined

2021-01-22 09:18 UTC, bpgoodwin commented on client/pages/supporters.vue
> +.full-width {
I think I addressed this with the 2nd to last commit? The "full-width" styling should just be so there is a decent & consistent gap between the cards and the edges of the screen on all devices, and to give that section contrast with the header.

2021-01-26 18:30 UTC, Drewbi approved these changes

2021-01-26 18:30 UTC, merged

2021-01-26 18:32 UTC, Drewbi commented
Made a few last changes and merged this. Good work :)