Han/contact
codersforcauses/bfa-rescue pull request #28
Opened 2021-01-09 06:54 UTC by Hanchooi

Basic Contact Form (First Draft)

2021-01-11 15:37 UTC, noobling approved these changes

2021-01-11 16:43 UTC, Drewbi requested changes
So I'm not sure why the website has that dark theme form but we definitely shouldn't copy that style as it doesn't make sense for the rest of the website. We also probably want to include the bio that's on the right of the contact page, unless you and Jeremiah decided not to include that intentionally.

2021-01-21 02:35 UTC, Hanchooi commented
About " the bio that's on the right of the contact page" :
In the issue that Daphne raised up, she mentioned that we should remove them.

About "Dark Theme":
Good idea. Roger that.

2021-01-21 03:40 UTC, Hanchooi commented
Changed to Light Themed, Added Title. Ready to merge.

2021-01-21 03:43 UTC, Drewbi requested changes

2021-01-21 03:43 UTC, Drewbi commented on client/components/contact/ContactForm.vue
> +  <v-sheet tile elevation="0" color="info">
I appreciate the colour choice but in the interest of keeping this consistent with the rest of the site we should just keep this as a white background.

2021-01-21 03:43 UTC, Drewbi commented on client/components/contact/ContactForm.vue
> +          <template #label>
I would use a label prop and change the styling using css instead of passing in a custom template.

2021-01-21 03:43 UTC, Drewbi commented on client/components/contact/ContactHeader.vue
> +      <h3>
You shouldn't be wrapping you p tags in h3 tags and then style them as h6 tags. Use 1 of these methods, not all of them.

2021-01-21 03:43 UTC, Drewbi commented on client/components/contact/ContactForm.vue
> +          v-model="message"
These fields haven't been added to the data yet.

2021-01-21 03:51 UTC, Hanchooi commented on client/components/contact/ContactForm.vue
> +  <v-sheet tile elevation="0" color="info">
ok

2021-01-21 03:54 UTC, Hanchooi commented on client/components/contact/ContactHeader.vue
> +      <h3>
uh oops. I don't know why I did this either. haha

2021-01-21 03:59 UTC, Hanchooi commented on client/components/contact/ContactForm.vue
> +          v-model="message"
Just added. But not sure if I did it correctly.

2021-01-21 04:01 UTC, Hanchooi commented on client/components/contact/ContactForm.vue
> +          <template #label>
Ah, sorry. I don't know how to do it this way though. Couldn't find example using this method.

2021-01-30 05:54 UTC, Hanchooi commented
Should be ready to merge.

2021-01-30 06:33 UTC, definitelyDaphne requested changes
Looking good overall
Noticed this little thing.. is there any reason why only the first name field has the clearable attribute?

Thanks

2021-01-30 09:20 UTC, merged