Ivy 4 home
codersforcauses/bfa-rescue pull request #39
Opened 2021-01-16 06:10 UTC by ivy0305

Still need to: 
- add links to the dog cards 
- fill in the descriptions for each of the sections (marked with ****)
- online application pages for the 'adopt a dog' and 'volunteer' section 
- re-upload pictures 
- link dog cards to back-end (I've only put in a few static ones to test it out)

2021-01-26 18:50 UTC, Drewbi commented
I feel like the online application part can be left for another issue and we can just add dead buttons for now.

Was thinking about home page designs also, I think a large hero text to one side would work well with this text: "We are building a retirement home for senior and special needs dogs."

Would have a dog pic on the right side with text on left, sorta like these designs: 
![ezgif com-webp-to-png](https://user-images.githubusercontent.com/38243574/105890472-5e3f8680-604a-11eb-9d8f-46a1723aaa80.png)
![0*J43zmSJHqzfPJY0_](https://user-images.githubusercontent.com/38243574/105890221-0d2f9280-604a-11eb-9bfa-a6e8b8339173.png)
![bad162b839068a08a9f876d27d87e602](https://user-images.githubusercontent.com/38243574/105890231-102a8300-604a-11eb-9e4b-41bdefe60b1d.png)

2021-01-31 13:28 UTC, Boosiegirl7 commented
I would love to help you guys this cause is very close to my heart. I've never done anything like this before, can you help me and I can learn to help you.  rmwells1978@gmail

2021-01-31 15:52 UTC, ivy0305 commented
Will probably need to check if the photos I've grabbed online (the paw and dog pic for the home page design) are okay to use

2021-02-02 04:40 UTC, Drewbi requested changes
Do you have the original source for the dog pic? Will probably not be a problem.

2021-02-02 04:40 UTC, Drewbi commented on client/components/home/DogCard.vue
> +          I'm available for adoption
This may need to be truncated at smaller sizes https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/

2021-02-02 04:40 UTC, Drewbi commented on client/components/home/Services.vue
> +  display: block;
Consider using flex box to center elements, The equivalent would be
```
<template>
  <div class="text-center d-flex flex-column justify-center align-center">
    <v-img :src="serviceimg" height="160" width="160" contain></v-img>
    <p class="servicename">{{ servicename }}</p>
  </div>
</template>
```

2021-02-03 17:23 UTC, Boosiegirl7 commented on client/components/home/DogCard.vue
> +          I'm available for adoption
Ok I'm new to this I would like to learn mo

2021-02-03 17:25 UTC, Boosiegirl7 commented on client/components/home/Services.vue
> +    <v-img :src="serviceimg" height="160" width="160" class="center"></v-img>
I'm wanting to learn how to help my local rescue with recourse

2021-02-03 17:29 UTC, Boosiegirl7 reviewed
I'm new to this you guys I'm going to try to do all this

2021-02-03 17:32 UTC, Boosiegirl7 commented
> Do you have the original source for the dog pic? Will probably not be a problem.

Yes I'm sure I can find it in my photos

2021-02-03 17:37 UTC, Boosiegirl7 reviewed
@Drewbi  I'm going to try my best to fix all the things you suggested

2021-02-03 17:49 UTC, Boosiegirl7 commented on client/components/home/Services.vue
> +  display: block;
Thank you  I took your advice and started the robot course I'll get it figured out and yes I took that photo and should have the orginal in my photos

2021-02-03 18:20 UTC, Boosiegirl7 commented
I couldn't find the photo that you have but here is another orginal I took
so what you need should be there. I'm sorry if I've messed anything up I
just would like to learn to contribute so I can help my local rescue.

On Sun, Jan 31, 2021, 9:52 AM ivy0305 <notifications@github.com> wrote:

> Will probably need to check if the photos I've grabbed online (the paw and
> dog pic for the home page design) are okay to use
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/codersforcauses/bfa-rescue/pull/39#issuecomment-770403089>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASPV2L6MSHAELZQB3ELI6DLS4V4DNANCNFSM4WFAIM5Q>
> .
>

2021-02-04 03:23 UTC, Drewbi commented
@Boosiegirl7 I appreciate your enthusiasm but this is @ivy0305 Pull request and it's better to not make changes to someone else's work without permission. I sent you an email so please check that and respond before continuing.

If you would like to find your own issue you are welcome to see what needs to be done with the pages we have completed vs the original website (bfarescue).

I'm happy you want to help but doing it in the correct way is important.

2021-02-04 05:37 UTC, ivy0305 commented
I've made the requested changes, let me know if anything else needs to be done!

2021-02-04 06:02 UTC, merged

2021-02-04 06:02 UTC, Drewbi commented
Good job :) looks great