Login Form
codersforcauses/bfa-rescue pull request #52
Opened 2021-01-29 06:03 UTC by Hanchooi

Basic Login Form

2021-01-30 06:43 UTC, definitelyDaphne approved these changes

2021-02-20 07:44 UTC, JeremiahPinto requested changes
A few minor changes to fix. Although I'm not sure the grid system is required for the login page since we want to set the max-width of the form. What you can instead do is remove `v-row` and `v-col`, set the form to have a max-width of a value that looks good and have a margin auto on the left and right sides. This should help make it more responsive. Good Job with getting the hang of vue and vuetify overall.

2021-02-20 07:44 UTC, JeremiahPinto commented on client/components/login/LoginForm.vue
> +          <v-form ref="form" v-model="valid" lazy-validation>
Ideally, we would want the form to handle submission rather than on click of a button.

```suggestion
          <v-form ref="form" v-model="valid" @submit.prevent.stop="validate()">
```

2021-02-20 07:44 UTC, JeremiahPinto commented on client/components/login/LoginForm.vue
> +  <v-sheet tile elevation="0" color="white">
Not sure if a `v-sheet` is required for the container

2021-02-20 07:44 UTC, JeremiahPinto commented on client/components/login/LoginForm.vue
> +              required
Remove required rules if validation is used to test if the field is required

2021-02-20 07:44 UTC, JeremiahPinto commented on client/components/login/LoginForm.vue
> +            </v-btn>
For forms, try not to disable a button if the field is invalid. Instead, check on submit of the form and give feedback where necessary. The reason for this is that the user may not know what is wrong with the form and feedback on submit is better for the user to know if they made a mistake.

```suggestion
            <v-btn type="submit" color="primary" class="mr-4">
              Login
            </v-btn>
```

2021-02-20 07:44 UTC, JeremiahPinto commented on client/components/login/LoginForm.vue
> +              label="Login ID"
Instead of `Login ID`, use `username`. It's a bit easier to understand.

2021-02-20 07:44 UTC, JeremiahPinto commented on client/components/login/LoginForm.vue
> +    },
These functions are unused

2021-02-20 07:44 UTC, JeremiahPinto commented on client/pages/login.vue
> +  </div>
Unnecessary use of `div`.
```suggestion
  <LoginForm />
```

2021-02-20 07:44 UTC, JeremiahPinto commented on client/pages/login.vue
> +}
Not sure if this is necessary since nuxt auto imports components for you.

2021-02-20 07:44 UTC, JeremiahPinto commented on client/components/login/LoginForm.vue
> +        <v-col cols="6" class="mx-auto">
This responsive layout will not be usable on anything smaller than a tablet.

2021-02-20 07:44 UTC, JeremiahPinto commented on client/components/login/LoginForm.vue
> +          <h2 style="text-align: center; margin-bottom: 1rem">Login</h2>
Try to use the vuetify in-built classes where possible.
```suggestion
          <h2 class="text-center mb-4">Login</h2>
```

2021-05-15 04:16 UTC, Drewbi approved these changes

2021-05-15 04:16 UTC, merged